version: '3.9'

services:
  db:
    image: postgres:17-alpine
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "100MB"
    container_name: app-payment-db
    hostname: app-payment-db
  app-01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-payment-01
    hostname: app-payment-01
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    environment:
      - DB_CONNECTION=Host=app-payment-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
      - PAYMENT_PROCESSOR=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "115MB"
  app-02:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-payment-02
    hostname: app-payment-02
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    environment:
      - DB_CONNECTION=Host=app-payment-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
      - PAYMENT_PROCESSOR=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "115MB"
  nginx:
    image: nginx:1.25-alpine
    container_name: app-payment-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-01
      - app-02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "20MB"
networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true